### ISSUE TITLE
OpenCilk 2.0 RC1 Issue with objdump of output

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#107]
When I run objdump an any output file which includes debug info, I get the error `objdump: DWARF error: invalid or unhandled FORM value: 0x25`

example file 
```
int main(int argc, char *argv[]) { return 0; }
```
When I run 
```
../opencilkv20/build/bin/clang++  -g   main.cpp  -o basic && objdump -S --disassemble basic > run_basic.dump
```
I get 
`objdump: DWARF error: invalid or unhandled FORM value: 0x25`
For reference
```
../opencilkv20/build/bin/clang++ --version
clang version 14.0.5 (https://github.com/OpenCilk/opencilk-project f51b7f1615e84757bfcc327a8e90371382db0e67)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

From some searching this seemed to be an issue with more modern form of clang, so I also tried with a base clang install and had no issues

```
../llvm-project/build/bin/clang++ --version
clang version 14.0.0 (https://github.com/llvm/llvm-project.git d50072f74e3ee50b750a618fcdf05739dec9542d)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by neboat** [comment]
Thanks for reporting this issue.

What happens if you add either the flag `-fdebug-default-version=4` or the flag `-gdwarf-4` at compile time?  That should change the DWARF version number to something that your copy of `objdump` supports, which should eliminate that error.

**Comment by wheatman** [comment]
Either seem to work, thank you 
Any idea why the default seems to be different than base clang?

**Comment by neboat** [comment]
I know that Clang 14 changed the default DWARF version from 4 to 5: https://releases.llvm.org/14.0.0/tools/clang/docs/ReleaseNotes.html#dwarf-support-in-clang.  According to those release notes, some platforms opt out of that version bump, but we haven't taken any particular steps on that front.

Out of curiosity, what platform are you testing on?

**Comment by wheatman** [comment]
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by neboat** [comment]
We've noted this issue in the release notes as a known limitation of the current release, so I'm closing this issue.
