### ISSUE TITLE
Crash with cilksan and O0

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#127]
### Describe the bug

The compiler crashes with the backtrace at the bottom 

### OpenCilk version

~/opencilkv20/build/bin/clang++ --version
clang version 14.0.6 (https://github.com/OpenCilk/opencilk-project fc90ded2b090672f84c58d12d8d85cd999eb6c1a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/opencilkv20/build/bin

### System information

- OS: Ubuntu 20.04.1 LTS
- CPU: Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz

### Steps to reproduce (include relevant output)

1. clone git@github.com:wheatman/concurrent-btrees.git commit a4521b7a9a76dee6d52ec0b6ceb64fb4e895abe4

2. build with `make CILK=1 SANITIZE=1 -B OPT=0`

[test-6c34fa.sh.txt](https://github.com/OpenCilk/opencilk-project/files/9309729/test-6c34fa.sh.txt)
[test-6c34fa.cpp.txt](https://github.com/OpenCilk/opencilk-project/files/9309730/test-6c34fa.cpp.txt)

### Backtrace

clang-14: /home/ubuntu/opencilkv20/opencilk/llvm/lib/Transforms/IPO/AlwaysInliner.cpp:86: llvm::PreservedAnalyses llvm::AlwaysInlinerPass::run(llvm::Module &, llvm::ModuleAnalysisManager &): Assertion `Res.isSuccess() && "unexpected failure to inline"' failed.
PLEASE submit a bug report to https://github.com/OpenCilk/opencilk-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/ubuntu/opencilkv20/build/bin/clang-14 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj -mrelax-all --mrelax-relocations -disable-free -clear-ast-before-backend -main-file-name test.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu cascadelake -target-feature -avx512pf -target-feature -tsxldtrk -target-feature +cx16 -target-feature +sahf -target-feature -tbm -target-feature -avx512ifma -target-feature -sha -target-feature +crc32 -target-feature -fma4 -target-feature -vpclmulqdq -target-feature +prfchw -target-feature +bmi2 -target-feature -cldemote -target-feature +fsgsbase -target-feature -ptwrite -target-feature -amx-tile -target-feature -uintr -target-feature -gfni -target-feature +popcnt -target-feature -widekl -target-feature +aes -target-feature -avx512bitalg -target-feature -movdiri -target-feature +xsaves -target-feature -avx512er -target-feature -avxvnni -target-feature -avx512fp16 -target-feature +avx512vnni -target-feature -amx-bf16 -target-feature -avx512vpopcntdq -target-feature -pconfig -target-feature +clwb -target-feature +avx512f -target-feature +xsavec -target-feature -clzero -target-feature +pku -target-feature +mmx -target-feature -lwp -target-feature -rdpid -target-feature -xop -target-feature +rdseed -target-feature -waitpkg -target-feature -kl -target-feature -movdir64b -target-feature -sse4a -target-feature +avx512bw -target-feature +clflushopt -target-feature +xsave -target-feature -avx512vbmi2 -target-feature +64bit -target-feature +avx512vl -target-feature -serialize -target-feature -hreset -target-feature +invpcid -target-feature +avx512cd -target-feature +avx -target-feature -vaes -target-feature -avx512bf16 -target-feature +cx8 -target-feature +fma -target-feature -rtm -target-feature +bmi -target-feature -enqcmd -target-feature +rdrnd -target-feature -mwaitx -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +avx2 -target-feature +fxsr -target-feature -wbnoinvd -target-feature +sse -target-feature +lzcnt -target-feature +pclmul -target-feature -prefetchwt1 -target-feature +f16c -target-feature +ssse3 -target-feature -sgx -target-feature -shstk -target-feature +cmov -target-feature -avx512vbmi -target-feature -amx-int8 -target-feature +movbe -target-feature -avx512vp2intersect -target-feature +xsaveopt -target-feature +avx512dq -target-feature +sse2 -target-feature +adx -target-feature +sse3 -mllvm -treat-scalable-fixed-error-as-warning -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fcoverage-compilation-dir=/home/ubuntu/concurrent-btrees/btree_tests -resource-dir /home/ubuntu/opencilkv20/build/lib/clang/14.0.6 -I ParallelTools/ -I ../ -D PARLAY_CILK -D NDEBUG -D ENABLE_TRACE_TIMER=0 -D CYCLE_TIMER=0 -D CILK=1 -D DEBUG=0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/x86_64-linux-gnu/c++/11 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../include/c++/11/backward -internal-isystem /home/ubuntu/opencilkv20/build/lib/clang/14.0.6/include -internal-isystem /usr/local/include -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/11/../../../../x86_64-linux-gnu/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O0 -Wall -Wextra -std=c++20 -fdeprecated-macro -fdebug-compilation-dir=/home/ubuntu/concurrent-btrees/btree_tests -ferror-limit 19 -fopencilk --opencilk-abi-bitcode=/home/ubuntu/opencilkv20/build/lib/clang/14.0.6/lib/x86_64-unknown-linux-gnu/libopencilk-asan-abi.bc -fsanitize=address,cilk,alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,return,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,unreachable,vla-bound,vptr -fsanitize-recover=alignment,array-bounds,bool,builtin,enum,float-cast-overflow,function,integer-divide-by-zero,nonnull-attribute,null,pointer-overflow,returns-nonnull-attribute,shift-base,shift-exponent,signed-integer-overflow,vla-bound,vptr -fsanitize-system-ignorelist=/home/ubuntu/opencilkv20/build/lib/clang/14.0.6/share/asan_ignorelist.txt -fsanitize-address-use-after-scope -fno-assume-sane-operator-new -fgnuc-version=4.2.1 -fno-implicit-modules -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/test-5844d9.o -x c++ test.cpp
1.      <eof> parser at end of file
2.      Optimizer
 #0 0x0000000002006003 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x2006003)
 #1 0x0000000002003d2e llvm::sys::RunSignalHandlers() (/home/ubuntu/opencilkv20/build/bin/clang-14+0x2003d2e)
 #2 0x00000000020064bf SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fe9200d33c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x143c0)
 #4 0x00007fe91fb2e03b raise /build/glibc-sMfBJT/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007fe91fb0d859 abort /build/glibc-sMfBJT/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007fe91fb0d729 get_sysdep_segment_value /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007fe91fb0d729 _nl_load_domain /build/glibc-sMfBJT/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007fe91fb1f006 (/lib/x86_64-linux-gnu/libc.so.6+0x34006)
 #9 0x00000000018aee34 llvm::AlwaysInlinerPass::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x18aee34)
#10 0x00000000031826ad llvm::detail::PassModel<llvm::Module, llvm::AlwaysInlinerPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x31826ad)
#11 0x000000000185bc84 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module> >::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x185bc84)
#12 0x000000000235351a (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >&, std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile> >&) BackendUtil.cpp:0:0
#13 0x0000000002346de1 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x2346de1)
#14 0x00000000030803ef clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x30803ef)
#15 0x0000000003b7f754 clang::ParseAST(clang::Sema&, bool, bool) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x3b7f754)
#16 0x0000000002a1d0a0 clang::FrontendAction::Execute() (/home/ubuntu/opencilkv20/build/bin/clang-14+0x2a1d0a0)
#17 0x000000000299912f clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x299912f)
#18 0x0000000002ad4773 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x2ad4773)
#19 0x00000000009eb097 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/ubuntu/opencilkv20/build/bin/clang-14+0x9eb097)
#20 0x00000000009e8da0 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#21 0x00000000009e8b34 main (/home/ubuntu/opencilkv20/build/bin/clang-14+0x9e8b34)
#22 0x00007fe91fb0f0b3 __libc_start_main /build/glibc-sMfBJT/glibc-2.31/csu/../csu/libc-start.c:342:3
#23 0x00000000009e5c6e _start (/home/ubuntu/opencilkv20/build/bin/clang-14+0x9e5c6e)
clang-14: error: unable to execute command: Aborted (core dumped)
clang-14: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 14.0.6 (https://github.com/OpenCilk/opencilk-project fc90ded2b090672f84c58d12d8d85cd999eb6c1a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/opencilkv20/build/bin
clang-14: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/test-9c6ff5.cpp
clang-14: note: diagnostic msg: /tmp/test-9c6ff5.sh
clang-14: note: diagnostic msg: 

********************
make: *** [Makefile:52: basic] Error 254

**Comment by neboat** [comment]
The fix for this issue has been merged with the next release.
