### ISSUE TITLE
Incorrect parallel execution with lambda with more than 2 captures 

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#147]
### Describe the bug

The simple explanation is that I have a lambda inside a cilk_for loop, which behaves correctly if I have two captures, but starts giving me the incorrect result if I pass in a third capture, even if I never touch the third capture.  One hint of what might be going on is that when I ran cilk_san it found races on multiple writes to my lambda, but my lambda was declared inside of the cilk_for, and thus each iteration should have its own copy which should make races impossible.

I attempted for awhile to make a minimal example, but it seems to be very sensitive to a number of seemingly unrelated things so I tried to simplify my example as much as possible.  The code can be found [test.txt](https://github.com/OpenCilk/opencilk-project/files/10063346/test.txt) (renamed from test.cpp to test.txt for upload)

For starters you can build it serially with 
`clang++ -Wall -Wextra -Ofast -g  -std=c++20 -gdwarf-4 -march=native -DNDEBUG -DCILK=0 -DOPENMP=0 -DDEBUG=0 -lrt -lm -lpthread -lm -ldl -latomic -ljemalloc -o basic test.cpp`
and then run it with `./basic 1000 1000` it should print out that it inserted a bunch of things and did some queries running 5 trials total.  Specifically it will not print "got the wrong answer :(" at the end.

You can then build it in parallel with `clang++ -Wall -Wextra -Ofast -g  -std=c++20 -gdwarf-4 -march=native -fopencilk -DPARLAY_CILK -DNDEBUG -DCILK=1 -DOPENMP=0 -DDEBUG=0 -lrt -lm -lpthread -lm -ldl -latomic -ljemalloc -o basic test.cpp` and when you run this build you should see it does end with the print "got the wrong answer :("

As a sanity check you can build it to run with openmp parallelism with `clang++ -Wall -Wextra -Ofast -g  -std=c++20 -gdwarf-4 -march=native -fopenmp -DNDEBUG -DCILK=0 -DOPENMP=1 -DDEBUG=0 -lrt -lm -lpthread -lm -ldl -latomic -ljemalloc -o basic test.cpp` and see that it is still correct.

Now if you go to line 1270 and remove the capture unused and then build it again with cilk, you will see that it now gets to the end without printing any errors.

If you put that back and instead comment out the definition of concurrent_map on lines 1189 to 1192, and comment in lines 1195 to 1202 for the second definition of concurrent map.  The first class is simply a wrapper around the second class, but this seems to make a difference.

If you now switch that back on and go the the body of the map_range_length around line 600.  If you comment out any of the three sched_yield in this function you will then get the correct answer.  You can also leave all of those in and instead comment out all the locking code in this function (which isn't necessary for this test since it is a read only test).

If you put the code back to the way it started and run it with cilk san you get the races that look like 

```
Race detected on location 7ffff82bb458
*    Write 48523e map_range_length<(lambda at test.cpp:1269:41)> /home/wheatman/concurrent-btrees/btree_tests/test.cpp:0:0
|        `-to variable f (declared at /home/wheatman/concurrent-btrees/btree_tests/test.cpp:1108)
|*   Write 48523e map_range_length<(lambda at test.cpp:1269:41)> /home/wheatman/concurrent-btrees/btree_tests/test.cpp:0:0
||       `-to variable f (declared at /home/wheatman/concurrent-btrees/btree_tests/test.cpp:1108)
\| Common calling context
 +  Parfor 48957e test_concurrent_microbenchmarks_map<unsigned long, 1024U, 1024U> /home/wheatman/concurrent-btrees/btree_tests/test.cpp:1256:7
 +    Call 484b63 main /home/wheatman/concurrent-btrees/btree_tests/test.cpp:1332:18
   Allocation context
    Stack object f (declared at /home/wheatman/concurrent-btrees/btree_tests/test.cpp:1108)
     Alloc 485e1a in test_concurrent_microbenchmarks_map<unsigned long, 1024U, 1024U> /home/wheatman/concurrent-btrees/btree_tests/test.cpp
      Call 484b63 main /home/wheatman/concurrent-btrees/btree_tests/test.cpp:1332:18
``` 
Which go away when you only have two captures in the lambda.  What is interesting is at least from my reading of the code is that the variable f which has the races should be a local variable inside of a single iteration of the cilk_for loop.

The other changes described above (commenting out the yields or locking), do actually make the race go away, they are not simply changing the timing avoiding the bug.

Sorry for the less than clear bug description let me know if anything doesn't make sense and I can try and clear it up.

### Expected behavior
For it to run the same in serial or parallel and pass the provided test.

### OpenCilk version

clang version 14.0.6 (https://github.com/OpenCilk/opencilk-project fc90ded2b090672f84c58d12d8d85cd999eb6c1a)

**Comment by neboat** [comment]
Thanks for reporting this issue.

I managed to replicate the core phenomenon, that the code seems to compile correctly when the lambda has 2 captures but not when it has 3 captures, even if the third capture is unused.  I also managed to replicate this issue at low optimization levels.

We'll look into what's going wrong and get back to you.

**Comment by VoxSciurorum** [comment]
Inside LLVM a lambda with captures is a variable with an anonymous and unique class type (here, `%class.anon` in the IR).  The lambda is constructed where it is written in the source code.  As for any other block scope fixed size variable, the `alloca` for the lambda is lifted to the beginning of the function, meaning space for the lambda is only allocated once instead of once per execution of the block where it appears.   This is a good optimization for serial code but it can introduce races.  Because this pattern is ubiquitous the OpenCilk compiler normally knows how to fix it, by moving the memory allocation into the same parallel construct as its use.  For some reason the complicated code for lambda initialization (involving casts to and from `i8*`) is not recognized by this pass.  I will keep looking for the reason why.

**Comment by VoxSciurorum** [comment]
As a workaround while I keep digging for the bug, if you pass the lambda by reference instead of value (`const F& f` instead of `F f`) it should work.

**Comment by VoxSciurorum** [comment]
This turns out to be the same bug as #148, which TB has a fix for.

**Comment by wheatman** [comment]
This seems fixed with the most recent version, if so the issue can be closed
