### ISSUE TITLE
Issues with debug symbols when using perf

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#172]
### Describe the bug
When I compile my code with cilk and then try and profile it with perf many of the symbols seem to not be attributed properly making performance debugging more difficult.

When I compile using cilk I get a perf output that looks like 
![image](https://github.com/OpenCilk/opencilk-project/assets/6783551/4a28b787-95e0-40e8-bf39-13f778e1b421)

I would expect to get something more like what I get when I compile and profile using parlaylib which is 

![image](https://github.com/OpenCilk/opencilk-project/assets/6783551/91d42a90-f003-464e-bc55-6caebdfbe9f0)

I note that this does not seem to happen when I tried to recreate it with some small examples.

### OpenCilk version

../opencilk201/build/bin/clang++ --version
clang version 14.0.6 (https://github.com/OpenCilk/opencilk-project f54e98722992462e042f0686c74f710277c92cdb)
Target: x86_64-unknown-linux-gnu
Thread model: posix

### System information

wsl Ubuntu 22.04.2 LTS

### Steps to reproduce (include relevant output)

1. clone git@github.com:wheatman/EdgeMapVertexMap.git
2. cd CSR
3. make CILK=1 -B
4. perf record ./basic -g slashdot.txt --algorithm cc --dump_output=false
5. perf report

[slasldot.txt](https://github.com/OpenCilk/opencilk-project/files/11781437/slasldot.txt)

rename the file to slashdot.adj

That file is a little small so that it looks like the functions which get lost are just small portions of the code, the file I used in the example images above was bigger and thus show that important functions are lost, but that bigger file was too big to upload.

**Comment by VoxSciurorum** [comment]
I can't compile the program.

The first problem was, the ParallelTools repository also needs to be cloned.  The second problem was, the program uses an internal feature of the C++ library implementation (`typename std::_Vector_base<T, std::allocator<T>>::_Vector_impl`) and does not compile on FreeBSD.

Now building on Linux with the extra repository cloned I have a missing file:
```
../include/EdgeMapVertexMap/internal/GraphHelpers.hpp:28:10: fatal error: 'cxxopts.hpp' file not found
#include "cxxopts.hpp"
```

**Comment by wheatman** [comment]
Ah, sorry about that.
The file is from here
https://github.com/jarro2783/cxxopts/tree/master/include

I thought it would have come in when you cloned since it's from a submodule.
But it's possible it was supposed to be a recursive clone and I messed it
up.

**Comment by VoxSciurorum** [comment]
I ran git submodule init/update and I was able to compile and run.  I reproduced the essence of the problem.  I don't see any symbols at all in perf output, only object+offset.

**Comment by neboat** [comment]
This problem has been fixed in the latest version of OpenCilk.
