### ISSUE TITLE
cilk and address sanitizers together cause the program to eat all memory and be killed 

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#197]
### Describe the bug

The following program when compiled with `-fsanitize=cilk,address` and then run, eats all memory and then is killed

```
//compiled with  ~/opencilk16/build/bin/clang++  -fopencilk -fsanitize=cilk,address del.cpp
#include <cilk/cilk.h>

int main() {

  int x[10] = {0};

  cilk_for(int i = 0; i < 10; i++) { x[i]++; }

  return 0;
}

```

### Expected behavior

The program to report no races and finish without being killed 

### OpenCilk version

clang version 16.0.6 (https://github.com/OpenCilk/opencilk-project aa4f4c0c6a59a9e42c3ef8cc8ef715f5ed8b7553)

**Comment by neboat** [comment]
This issue is fixed in the latest release.
