### ISSUE TITLE
make with -O0 and CSI instrumentation fails

### ISSUE THREAD

**Issue by PhilMurzynowski** [OpenCilk/opencilk-project#24]
make with -O0 and CSI instrumentation fails

ubuntu@6172vm:~/homework6$ make -B CSI=1 LINREG=1 ./fib_serial
clang -o fib_serial.o -flto  -fcsi -c fib_serial.c -march=native -O0 -g
Unknown type!
UNREACHABLE executed at /software/deps/opencilk-project/llvm/lib/CodeGen/ValueTypes.cpp:316!
Stack dump:
0.      Program arguments: /usr/bin/clang-9 -cc1 -triple x86_64-unknown-linux-gnu -emit-llvm-bc -flto -flto-unit -disable-free -main-file-name fib_serial.c -mrelocation-model static -mthread-model posix -mdisable-fp-elim -fmath-errno -masm-verbose -mconstructor-aliases -munwind-tables -fuse-init-array -target-cpu skylake -target-feature +sse2 -target-feature +cx16 -target-feature +sahf -target-feature -tbm -target-feature -avx512ifma -target-feature -sha -target-feature -gfni -target-feature -fma4 -target-feature -vpclmulqdq -target-feature +prfchw -target-feature +bmi2 -target-feature -cldemote -target-feature +fsgsbase -target-feature -ptwrite -target-feature +xsavec -target-feature +popcnt -target-feature -mpx -target-feature +aes -target-feature -avx512bitalg -target-feature -movdiri -target-feature +xsaves -target-feature -avx512er -target-feature -avx512vnni -target-feature -avx512vpopcntdq -target-feature -pconfig -target-feature -clwb -target-feature -avx512f -target-feature -clzero -target-feature -pku -target-feature +mmx -target-feature -lwp -target-feature -rdpid -target-feature -xop -target-feature +rdseed -target-feature -waitpkg -target-feature -movdir64b -target-feature -sse4a -target-feature -avx512bw -target-feature +clflushopt -target-feature +xsave -target-feature -avx512vbmi2 -target-feature +64bit -target-feature -avx512vl -target-feature +invpcid -target-feature -avx512cd -target-feature +avx -target-feature -vaes -target-feature +cx8 -target-feature +fma -target-feature -rtm -target-feature +bmi -target-feature -enqcmd -target-feature +rdrnd -target-feature -mwaitx -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +avx2 -target-feature +fxsr -target-feature -wbnoinvd -target-feature +sse -target-feature +lzcnt -target-feature +pclmul -target-feature -prefetchwt1 -target-feature +f16c -target-feature +ssse3 -target-feature -sgx -target-feature -shstk -target-feature +cmov -target-feature -avx512vbmi -target-feature -avx512bf16 -target-feature +movbe -target-feature +xsaveopt -target-feature -avx512dq -target-feature +adx -target-feature -avx512pf -target-feature +sse3 -dwarf-column-info -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -coverage-notes-file /home/ubuntu/homework6/fib_serial.gcno -resource-dir /usr/lib/clang/9.1.1 -internal-isystem /usr/local/include -internal-isystem /usr/lib/clang/9.1.1/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O0 -fdebug-compilation-dir /home/ubuntu/homework6 -ferror-limit 19 -fmessage-length 0 -fcsi -fobjc-runtime=gcc -fdiagnostics-show-option -fcolor-diagnostics -faddrsig -o fib_serial.o -x c fib_serial.c
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'ComprehensiveStaticInstrumentation' on module 'fib_serial.c'.
 #0 0x0000556644622f4a llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/usr/bin/clang-9+0x1a82f4a)
 #1 0x0000556644620b1c llvm::sys::RunSignalHandlers() (/usr/bin/clang-9+0x1a80b1c)
 #2 0x0000556644620c6c SignalHandler(int) (/usr/bin/clang-9+0x1a80c6c)
 #3 0x00007f5e770598a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #4 0x00007f5e76151f47 raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
 #5 0x00007f5e761538b1 abort /build/glibc-2ORdQG/glibc-2.27/stdlib/abort.c:81:0
 #6 0x00005566445bd47a (/usr/bin/clang-9+0x1a1d47a)
 #7 0x0000556643dbd193 (/usr/bin/clang-9+0x121d193)
 #8 0x0000556643dbd1f1 llvm::EVT::getEVT(llvm::Type*, bool) (/usr/bin/clang-9+0x121d1f1)
 #9 0x0000556643d96f7d llvm::TargetLoweringBase::getTypeLegalizationCost(llvm::DataLayout const&, llvm::Type*) const (/usr/bin/clang-9+0x11f6f7d)
#10 0x000055664376f3f0 llvm::X86TTIImpl::getMemoryOpCost(unsigned int, llvm::Type*, unsigned int, unsigned int, llvm::Instruction const*) (/usr/bin/clang-9+0xbcf3f0)
#11 0x0000556643b741c3 llvm::TargetTransformInfo::getMemoryOpCost(unsigned int, llvm::Type*, unsigned int, unsigned int, llvm::Instruction const*) const (/usr/bin/clang-9+0xfd41c3)
#12 0x0000556643b77194 llvm::TargetTransformInfo::getInstructionThroughput(llvm::Instruction const*) const (/usr/bin/clang-9+0xfd7194)
#13 0x000055664553b2a8 llvm::SizeTable::add(llvm::BasicBlock const&, llvm::TargetTransformInfo*) (/usr/bin/clang-9+0x299b2a8)
#14 0x000055664553cb18 llvm::CSIImpl::instrumentBasicBlock(llvm::BasicBlock&) (/usr/bin/clang-9+0x299cb18)
#15 0x0000556645544dc8 llvm::CSIImpl::instrumentFunction(llvm::Function&) (.part.927) (/usr/bin/clang-9+0x29a4dc8)
#16 0x0000556645545a64 llvm::CSIImpl::run() (/usr/bin/clang-9+0x29a5a64)
#17 0x0000556645545ca1 (anonymous namespace)::ComprehensiveStaticInstrumentationLegacyPass::runOnModule(llvm::Module&) (.part.928) (/usr/bin/clang-9+0x29a5ca1)
#18 0x00005566440e5484 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/usr/bin/clang-9+0x1545484)
#19 0x000055664484689f (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/bin/clang-9+0x1ca689f)
#20 0x000055664484858a clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/usr/bin/clang-9+0x1ca858a)
#21 0x000055664529d241 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/usr/bin/clang-9+0x26fd241)
#22 0x0000556645cd9d39 clang::ParseAST(clang::Sema&, bool, bool) (/usr/bin/clang-9+0x3139d39)
#23 0x000055664529a81f clang::CodeGenAction::ExecuteAction() (/usr/bin/clang-9+0x26fa81f)
#24 0x0000556644d26129 clang::FrontendAction::Execute() (/usr/bin/clang-9+0x2186129)
#25 0x0000556644ceade0 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/usr/bin/clang-9+0x214ade0)
#26 0x0000556644dcfe9c clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/usr/bin/clang-9+0x222fe9c)
#27 0x0000556643742816 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-9+0xba2816)
#28 0x00005566436e3e1d main (/usr/bin/clang-9+0xb43e1d)
#29 0x00007f5e76134b97 __libc_start_main /build/glibc-2ORdQG/glibc-2.27/csu/../csu/libc-start.c:344:0
#30 0x000055664373ea0a _start (/usr/bin/clang-9+0xb9ea0a)
clang-9: error: unable to execute command: Aborted (core dumped)
clang-9: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 9.1.1 
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
clang-9: note: diagnostic msg: PLEASE submit a bug report to https://github.com/OpenCilk/opencilk-project/issues and include the crash backtrace, preprocessed source, and associated run script.
clang-9: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-9: note: diagnostic msg: /tmp/fib_serial-406081.c
clang-9: note: diagnostic msg: /tmp/fib_serial-406081.sh
clang-9: note: diagnostic msg: 

********************
Makefile:47: recipe for target 'fib_serial.o' failed
make: *** [fib_serial.o] Error 254

[files.zip](https://github.com/OpenCilk/opencilk-project/files/5412260/files.zip)

**Comment by neboat** [comment]
Thanks for the bug report.  I was able to reproduce the behavior on my system from the files your provided, so I can now investigate the issue.

**Comment by neboat** [comment]
This issue has been resolved in version 1.0.
