### ISSUE TITLE
Assertion failure in PopCleanupBlock compiling catch block

### ISSUE THREAD

**Issue by VoxSciurorum** [OpenCilk/opencilk-project#266]
Assertion failure with attached reproducer:
```
Assertion failed: (!EHStack.empty() && "cleanup stack is empty!"), function PopCleanupBlock, file /data/Cilk/opencilk-project/clang/lib/CodeGen/CGCleanup.cpp, line 670.
```
If I remove the `_Cilk_sync` in the catch block the program compiles but crashes at runtime if an exception is thrown.
[grain-eea328.cpp.txt](https://github.com/user-attachments/files/16788142/grain-eea328.cpp.txt)
[grain-eea328.sh.txt](https://github.com/user-attachments/files/16788144/grain-eea328.sh.txt)

**Comment by VoxSciurorum** [comment]
Simpler test case:
```c++
extern int f();

void g() {
  try {
    f();
  } catch (int x) {
    _Cilk_sync;
  }
}
```
Compile with `clang++ -O1`.

**Comment by VoxSciurorum** [comment]
`TaskFrameScope::TaskFrameScope` pushes a cleanup if `CGF.CurSyncRegion` is not null.  `TaskFrameScope::~TaskFrameScope` pops a cleanup if `CGF.CurSyncRegion` is not null.  But `CGF.CurSyncRegion` has changed from null to non-null between construction and destruction.  Should the destructor be testing `TaskFrame` instead of `CGF.CurSyncRegion` so it pops a cleanup only if one was pushed?

**Comment by neboat** [comment]
Yes, that change sounds good to me.

I also managed to reproduce the runtime crash you encountered with the original test case.  I'm looking into that crash.
