### ISSUE TITLE
try inside cilk_scope breaks CFG

### ISSUE THREAD

**Issue by VoxSciurorum** [OpenCilk/opencilk-project#287]
In the test case below, with the options given in the RUN line, a function is miscompiled.  The only return instruction returns 3, but the `return 3;` statement is unreachable.  The function can only return 1 or 2.

Tested on amd64, Mac and FreeBSD.

Here the `_Cilk_scope` is meaningless.  The original test case had spawns.

```cpp
// RUN: %clang_cc1 %s -x c++ -O1 -fcxx-exceptions -fexceptions -fopencilk -mllvm -use-opencilk-runtime-bc=false -mllvm -debug-abi-calls=true -verify -S -emit-llvm -o - | FileCheck %s
// expected-no-diagnostics
// XFAIL
extern int maybe_throws(int);

// CHECK-LABEL: _Z9function4v
int function4()
{
  _Cilk_scope {
    try {
// CHECK: i32 @_Z12maybe_throwsi
      maybe_throws(1);
// CHECK: ret i32 1
      return 1;
    } catch (...) {
// CHECK: ret i32 2
      return 2;
    }
  }
// This return is unreachable.
// CHECK-NOT: ret i32 3
  return 3;
}
```

**Comment by VoxSciurorum** [comment]
Is this related to the bug fixed by d27bb4c1f93db820c11548215823138f8f3ebbdb ("Fix simplification of trivial unwind blocks for detaches and their spawned tasks")?

**Comment by neboat** [comment]
PR #289 has a simple fix that seems to address the test case you shared.  The fix isn't ideal, but I believe it's semantically correct and may be the simplest way to address the issue.

Does that PR fix the issue on your end?

**Comment by neboat** [comment]
Closing this issue, which #289 fixed.
