### ISSUE TITLE
Problems when using cilkscale tool

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#29]
I get undefined references when I try and compile with cilkscale 

For a minimal example I created a one line file 
main.cpp
`int main() { return 0; }`

I compiled it with the command 
`../OpenCilk-9.0.1-Linux/bin/clang++  -fopencilk -fcsi -lopencilk -L../OpenCilk-9.0.1-Linux//lib/clang/9.0.1/lib/x86_64-unknown-linux-gnu -l:libclang_rt.cilkscale.a`

The errors are 
/tmp/main-877cc6.o: In function `cilk_main`:
main.cpp:(.text+0x23): undefined reference to `__csi_func_entry`
main.cpp:(.text+0x42): undefined reference to `__csi_bb_entry`
main.cpp:(.text+0x67): undefined reference to `__csi_before_alloca`
main.cpp:(.text+0x81): undefined reference to `__csi_after_alloca`
main.cpp:(.text+0xb1): undefined reference to `__csi_before_store`
main.cpp:(.text+0xd2): undefined reference to `__csi_after_store`
main.cpp:(.text+0xdf): undefined reference to `__csi_bb_exit`
main.cpp:(.text+0xfe): undefined reference to `__csi_func_exit`
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)

../OpenCilk-9.0.1-Linux/bin/clang++ --version
```
clang version 9.0.1 (git@github.com:CilkHub/opencilk-project.git 48265098754b785d1b06cb08d8e22477a003efcd)
Target: x86_64-unknown-linux-gnu
Thread model: posix
```

**Comment by neboat** [comment]
A couple comments:
- I advise against using `-lopencilk`.  That flag is not sufficient for linking against the OpenCilk runtime.  Just use the `-fopencilk` when compiling or linking an OpenCilk program.
- To use Cilkscale, don't use `-fcsi -L../OpenCilk-9.0.1-Linux//lib/clang/9.0.1/lib/x86_64-unknown-linux-gnu -l:libclang_rt.cilkscale.a`.  Instead, just use `-fcilktool=cilkscale`.
- I don't see where that compile command is actually compiling `main.cpp`.  You might be getting linking problems based on the order of arguments.  I believe those problems should be resolved by using `-fcilktool=cilkscale`.

Cheers,
TB

**Comment by wheatman** [comment]
Thank you,
Those were the issues
