### ISSUE TITLE
compiler crash with pgo on release 1

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#43]
trying to compile with pgo enabled causes a compiler crash with the following assertion error

clang-10: /home/neboat/opencilk/llvm/include/llvm/IR/Instructions.h:2741: llvm::Value *llvm::PHINode::getIncomingValueForBlock(const llvm::BasicBlock *) const: Assertion `Idx >= 0 && "Invalid basic block argument!"' failed.

This is the same code #42 but seems to crash before the link step so I think the issues are not related.

The .sh .cpp and compiler output are all attached 
[error.sh.txt](https://github.com/OpenCilk/opencilk-project/files/6244565/error.sh.txt)
[errer.cpp.txt](https://github.com/OpenCilk/opencilk-project/files/6244566/errer.cpp.txt)
[error.log.txt](https://github.com/OpenCilk/opencilk-project/files/6244567/error.log.txt)

**Comment by neboat** [comment]
This issue has been fixed in version 1.1.
