### ISSUE TITLE
Compiler crash with "mismatched subprogram between llvm.dbg.value variable and !dbg attachment"

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#51]
I got a compiler crash.

Many things of the form

mismatched subprogram between llvm.dbg.value variable and !dbg attachment
  call void @llvm.dbg.value(metadata %"struct.basic_node<weight_balanced_tree::data, std::pair<std::pair<unsigned int, tree_plus::treeplus>, unsigned long> >::node"* %20, metadata !401801, metadata !DIExpression()), !dbg !401829
label %if.then.otd1
void (%"struct.basic_node<weight_balanced_tree::data, std::pair<std::pair<unsigned int, tree_plus::treeplus>, unsigned long> >::node"**)* @_ZN5utilsL14fork_no_resultIZN2gcIN20weight_balanced_tree7balanceI8aug_nodeINS2_4dataE18aug_map_full_entryIN29sym_immutable_graph_tree_plus12vertex_entryEEEEEE19decrement_recursiveEPN10basic_nodeIS5_St4pairISE_IjN9tree_plus8treeplusEEmEE4nodeEbEUlvE_ZNSC_19decrement_recursiveESL_bEUlvE0_EEvbT_T0_.outline_det.achd.i.otd1
!401801 = !DILocalVariable(name: "t", arg: 1, scope: !400029, file: !15556, line: 34, type: !400040)
!400029 = distinct !DISubprogram(name: "decrement_recursive", linkageName: "_ZN2gcIN20weight_balanced_tree7balanceI8aug_nodeINS0_4dataE18aug_map_full_entryIN29sym_immutable_graph_tree_plus12vertex_entryEEEEEE19decrement_recursiveEPN10basic_nodeIS3_St4pairISC_IjN9tree_plus8treeplusEEmEE4nodeEb", scope: !400030, file: !15556, line: 34, type: !401774, scopeLine: 34, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !30, declaration: !401773, retainedNodes: !401800)
!401829 = !DILocation(line: 0, scope: !35264, inlinedAt: !401822)
!35264 = distinct !DISubprogram(name: "decrement_recursive", linkageName: "_ZN2gcIN20weight_balanced_tree7balanceI8aug_nodeINS0_4dataE18aug_map_full_entryIN29sym_immutable_graph_tree_plus12vertex_entryEEEEEE19decrement_recursiveEPN10basic_nodeIS3_St4pairISC_IjN9tree_plus8treeplusEEmEE4nodeEb", scope: !19593, file: !15556, line: 34, type: !19606, scopeLine: 34, flags: DIFlagPrototyped | DIFlagAllCallsDescribed, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !30, declaration: !19605, retainedNodes: !35265)

The full output and error files are here 
[run_batch_updates-90cff2.sh.txt](https://github.com/OpenCilk/opencilk-project/files/6392753/run_batch_updates-90cff2.sh.txt)
[run_batch_updates-90cff2.cpp.txt](https://github.com/OpenCilk/opencilk-project/files/6392754/run_batch_updates-90cff2.cpp.txt)
[clang10.out.txt](https://github.com/OpenCilk/opencilk-project/files/6392755/clang10.out.txt)

I am running 

clang version 10.0.1 (git@github.com:OpenCilk/opencilk-project.git 8435006eea5d32f9cf895a666496b89613e2cbc1)

I believe I had this same code working a few months ago so I tried with 

clang version 9.0.1 (https://github.com/OpenCilk/opencilk-project.git 48265098754b785d1b06cb08d8e22477a003efcd)

but it also crashed, I don't see a specific error, but it gives a dump and a trace
The full output is attached, but it seems to be something with this
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'Function Pass Manager' on module 'tools/run_batch_updates.cpp'.
4.      Running pass 'Loop Pass Manager' on function '@_ZN4pbbs13bucket_sort_rISt5tupleIJjjEESt4lessIS2_EEEvNS_5rangeIPT_EES8_T0_bb'
5.      Running pass 'Stripmine Tapir loops' on basic block '%197'

[run_batch_updates-2cbddf.sh.txt](https://github.com/OpenCilk/opencilk-project/files/6392786/run_batch_updates-2cbddf.sh.txt)
[run_batch_updates-2cbddf.cpp.txt](https://github.com/OpenCilk/opencilk-project/files/6392787/run_batch_updates-2cbddf.cpp.txt)
[clang9.out.txt](https://github.com/OpenCilk/opencilk-project/files/6392788/clang9.out.txt)

**Comment by neboat** [comment]
This issue has been fixed in version 1.1.
