### ISSUE TITLE
seg fault only on 1.1 with PGO

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#78]
### Describe the bug

I am trying to use parlaylib and when I try and sort numbers and compile with pgo I get a segfault.  This does not happen if you don't compile with PGO, it didn't happen with the 1.0 verison, and it does not happen with clang-12 standard version

### Expected behavior
not to give me a segfault

### OpenCilk version
clang version 12.0.0 (git@github.com:OpenCilk/opencilk-project.git 5d2851d7d0e689ecb3b893aa6abd12390b838c4b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/OpenCilk-12.0.0-Linux/bin

- Distribution method: 
- downloaded with OpenCilk-1.1-LLVM-12.0.0-Ubuntu-20.04-x86_64.sh*

### System information

- OS: distribution, version 
- "Ubuntu 20.04.1 LTS"
- Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz

### Steps to reproduce (include relevant output)

1. clone https://github.com/cmuparlay/parlaylib

2. use the following small program

```
#include "parlaylib/include/parlay/primitives.h"
#include <cstdio>
#include <limits>
#include <random> // mt19937 and uniform_int_distribution
#include <vector>

template <class T> std::vector<T> create_random_data(size_t n, size_t max_val) {

  std::mt19937_64 eng; // a source of random data

  std::uniform_int_distribution<T> dist(0, max_val);
  std::vector<T> v(n);

  generate(begin(v), end(v), bind(dist, eng));
  return v;
}
int main(int32_t argc, char *argv[]) {
  uint64_t max_size = std::strtol(argv[1], nullptr, 10);
  auto data_vector = create_random_data<uint64_t>(
      max_size, std::numeric_limits<uint64_t>::max());
  parlay::integer_sort_inplace(data_vector);
  printf("max found was %lu\n", data_vector[max_size - 1]);
  return 0;
}

```

compile it with PGO with the following 4 commands
```
clang++ -Wall -Wextra -O3 -g  -std=c++17 -fopencilk -DPARLAY_CILK -lrt -lm -lpthread  -fprofile-instr-generate -o profile del.cpp
./profile 10000
llvm-profdata merge -output=code.profdata default.profraw
clang++ -Wall -Wextra -O3 -g  -std=c++17 -fopencilk -DPARLAY_CILK -lrt -lm -lpthread  -fprofile-instr-use=code.profdata -o opt del.cpp
```

3. get a segfault

### Working example code
compile the same code with 
```
clang++ -Wall -Wextra -O3 -g  -std=c++17 -fopencilk -DPARLAY_CILK -lrt -lm -lpthread  -o basic del.cpp
```
to see the expected output

### Additional comments
when I try the same code with the old version
clang version 10.0.1 (git@github.com:OpenCilk/opencilk-project.git 8435006eea5d32f9cf895a666496b89613e2cbc1)

I get the expected output

**Comment by neboat** [comment]
This issue has been fixed in the latest release.
