### ISSUE TITLE
compiler crash with PGO

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#83]
### Describe the bug

The compiler crashes after the following assertion

clang-12: /home/neboat/opencilk-project/llvm/lib/Transforms/Utils/BreakCriticalEdges.cpp:154: llvm::BasicBlock *llvm::SplitCriticalEdge(llvm::Instruction *, unsigned int, const llvm::CriticalEdgeSplittingOptions &, const llvm::Twine &): Assertion `(Options.SplitDetachContinue && Options.DT) && "Cannot split critical continuation edge from a detach"' failed.

### Expected behavior

For the compiler not to crash

### OpenCilk version

:~/SSTGraph_open_source/SSTGraph$ ../../OpenCilk-12.0.0-Linux/bin/clang++ --versionclang version 12.0.0 (git@github.com:OpenCilk/opencilk-project.git 5d2851d7d0e689ecb3b893aa6abd12390b838c4b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/SSTGraph_open_source/SSTGraph/../../OpenCilk-12.0.0-Linux/bin

- Distribution method: from .sh archive 

### System information

~/SSTGraph_open_source/SSTGraph$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

### Steps to reproduce (include relevant output)

1. clone https://github.com/wheatman/SSTGraph

2. build with `CXX=../../OpenCilk-12.0.0-Linux/bin/clang++ make opt CILK=1`

### Additional comments

full backtrace

clang-12: /home/neboat/opencilk-project/llvm/lib/Transforms/Utils/BreakCriticalEdges.cpp:154: llvm::BasicBlock *llvm::SplitCriticalEdge(llvm::Instruction *, unsigned int, const llvm::CriticalEdgeSplittingOptions &, const llvm::Twine &): Assertion `(Options.SplitDetachContinue && Options.DT) && "Cannot split critical continuation edge from a detach"' failed.
PLEASE submit a bug report to https://github.com/OpenCilk/opencilk-project/issues and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: /home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12 -cc1 -triple x86_64-unknown-linux-gnu -emit-obj --mrelax-relocations -disable-free -main-file-name run.cpp -mrelocation-model static -mframe-pointer=none -menable-no-infs -menable-no-nans -fmath-errno -fno-signed-zeros -freciprocal-math -ffp-contract=fast -fno-rounding-math -ffp-exception-behavior=ignore -ffinite-math-only -mconstructor-aliases -munwind-tables -target-cpu cascadelake -target-feature +sse2 -target-feature -tsxldtrk -target-feature +cx16 -target-feature +sahf -target-feature -tbm -target-feature -avx512ifma -target-feature -sha -target-feature -gfni -target-feature -fma4 -target-feature -vpclmulqdq -target-feature +prfchw -target-feature +bmi2 -target-feature -cldemote -target-feature +fsgsbase -target-feature -ptwrite -target-feature -amx-tile -target-feature -uintr -target-feature +popcnt -target-feature -widekl -target-feature +aes -target-feature -avx512bitalg -target-feature -movdiri -target-feature +xsaves -target-feature -avx512er -target-feature -avxvnni -target-feature +avx512vnni -target-feature -amx-bf16 -target-feature -avx512vpopcntdq -target-feature -pconfig -target-feature +clwb -target-feature +avx512f -target-feature +xsavec -target-feature -clzero -target-feature +pku -target-feature +mmx -target-feature -lwp -target-feature -rdpid -target-feature -xop -target-feature +rdseed -target-feature -waitpkg -target-feature -kl -target-feature -movdir64b -target-feature -sse4a -target-feature +avx512bw -target-feature +clflushopt -target-feature +xsave -target-feature -avx512vbmi2 -target-feature +64bit -target-feature +avx512vl -target-feature -serialize -target-feature -hreset -target-feature +invpcid -target-feature +avx512cd -target-feature +avx -target-feature -vaes -target-feature -avx512bf16 -target-feature +cx8 -target-feature +fma -target-feature -rtm -target-feature +bmi -target-feature -enqcmd -target-feature +rdrnd -target-feature -mwaitx -target-feature +sse4.1 -target-feature +sse4.2 -target-feature +avx2 -target-feature +fxsr -target-feature -wbnoinvd -target-feature +sse -target-feature +lzcnt -target-feature +pclmul -target-feature -prefetchwt1 -target-feature +f16c -target-feature +ssse3 -target-feature -sgx -target-feature -shstk -target-feature +cmov -target-feature -avx512vbmi -target-feature -amx-int8 -target-feature +movbe -target-feature -avx512vp2intersect -target-feature +xsaveopt -target-feature +avx512dq -target-feature +adx -target-feature -avx512pf -target-feature +sse3 -fno-split-dwarf-inlining -debug-info-kind=limited -dwarf-version=4 -debugger-tuning=gdb -fprofile-instrument-path=code-%p.profraw -fprofile-instrument=clang -fprofile-arcs -resource-dir /home/ubuntu/OpenCilk-12.0.0-Linux/lib/clang/12.0.0 -D OPENMP=0 -D CILK=1 -D TINYSET_32=0 -D NO_INLINE_TINYSET=0 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/x86_64-linux-gnu/c++/10 -internal-isystem /usr/lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/backward -internal-isystem /usr/local/include -internal-isystem /home/ubuntu/OpenCilk-12.0.0-Linux/lib/clang/12.0.0/include -internal-externc-isystem /usr/include/x86_64-linux-gnu -internal-externc-isystem /include -internal-externc-isystem /usr/include -O3 -Wall -Wno-address-of-packed-member -Wextra -std=c++17 -fdeprecated-macro -fdebug-compilation-dir /home/ubuntu/SSTGraph_open_source/SSTGraph -ferror-limit 19 -fopencilk --opencilk-abi-bitcode=/home/ubuntu/OpenCilk-12.0.0-Linux/lib/clang/12.0.0/lib/x86_64-unknown-linux-gnu/libopencilk-abi.bc -fgnuc-version=4.2.1 -fcxx-exceptions -fexceptions -fcolor-diagnostics -vectorize-loops -vectorize-slp -stripmine-loops -faddrsig -o /tmp/run-7ba690.o -x c++ run.cpp
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'GCOV Profiler' on module 'run.cpp'.
 #0 0x00000000057b8a43 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x57b8a43)
 #1 0x00000000057b678e llvm::sys::RunSignalHandlers() (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x57b678e)
 #2 0x00000000057b8f0f SignalHandler(int) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x57b8f0f)
 #3 0x00007f9052c233c0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x153c0)
 #4 0x00007f90526b718b raise /build/glibc-eX1tMB/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007f9052696859 abort /build/glibc-eX1tMB/glibc-2.31/stdlib/abort.c:81:7
 #6 0x00007f9052696729 get_sysdep_segment_value /build/glibc-eX1tMB/glibc-2.31/intl/loadmsgcat.c:509:8
 #7 0x00007f9052696729 _nl_load_domain /build/glibc-eX1tMB/glibc-2.31/intl/loadmsgcat.c:970:34
 #8 0x00007f90526a7f36 (/lib/x86_64-linux-gnu/libc.so.6+0x36f36)
 #9 0x00000000057d3f21 llvm::SplitCriticalEdge(llvm::Instruction*, unsigned int, llvm::CriticalEdgeSplittingOptions const&, llvm::Twine const&) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x57d3f21)
#10 0x00000000052a7308 (anonymous namespace)::GCOVProfiler::emitProfileNotes(llvm::NamedMDNode*, bool, llvm::function_ref<llvm::BlockFrequencyInfo* (llvm::Function&)>, llvm::function_ref<llvm::BranchProbabilityInfo* (llvm::Function&)>, llvm::function_ref<llvm::TargetLibraryInfo const& (llvm::Function&)>) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x52a7308)
#11 0x00000000052a538f (anonymous namespace)::GCOVProfiler::runOnModule(llvm::Module&, llvm::function_ref<llvm::BlockFrequencyInfo* (llvm::Function&)>, llvm::function_ref<llvm::BranchProbabilityInfo* (llvm::Function&)>, std::function<llvm::TargetLibraryInfo const& (llvm::Function&)>) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x52a538f)
#12 0x00000000052a59b6 (anonymous namespace)::GCOVProfilerLegacyPass::runOnModule(llvm::Module&) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x52a59b6)
#13 0x0000000004f496b7 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x4f496b7)
#14 0x0000000005a313e3 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x5a313e3)
#15 0x0000000006190743 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x6190743)
#16 0x000000000718b0d3 clang::ParseAST(clang::Sema&, bool, bool) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x718b0d3)
#17 0x00000000060d93b3 clang::FrontendAction::Execute() (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x60d93b3)
#18 0x0000000006016683 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x6016683)
#19 0x000000000618a732 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x618a732)
#20 0x0000000003667017 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x3667017)
#21 0x0000000003664f62 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x3664f62)
#22 0x0000000003664c04 main (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x3664c04)
#23 0x00007f90526980b3 __libc_start_main /build/glibc-eX1tMB/glibc-2.31/csu/../csu/libc-start.c:342:3
#24 0x0000000003661c6e _start (/home/ubuntu/OpenCilk-12.0.0-Linux/bin/clang-12+0x3661c6e)
clang-12: error: unable to execute command: Aborted (core dumped)
clang-12: error: clang frontend command failed due to signal (use -v to see invocation)
clang version 12.0.0 (git@github.com:OpenCilk/opencilk-project.git 5d2851d7d0e689ecb3b893aa6abd12390b838c4b)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/ubuntu/SSTGraph_open_source/SSTGraph/../../OpenCilk-12.0.0-Linux/bin
clang-12: note: diagnostic msg: 
********************

requested files 

[run-27b796.cpp.txt](https://github.com/OpenCilk/opencilk-project/files/7830704/run-27b796.cpp.txt)
[run-27b796.sh.txt](https://github.com/OpenCilk/opencilk-project/files/7830706/run-27b796.sh.txt)

**Comment by wheatman** [comment]
Did some more testing, and it seems like PGO just doesn't work at all

I used the following program

```
#include <cilk/cilk.h>

int main(int argc, char *argv[]) {
  cilk_for(int i = 0; i < 100; i++) {}
  return 0;
}

```
Compiled it with the following command 

`../opencilk-project/build/bin/clang++ -fprofile-arcs -fprofile-instr-generate=code-%p.profraw  -O3  -fopencilk  run.cpp`

And I get effectively the same crash 
If I use any optimization flag expect for -O0 it crashes.

As a note this does not crash with the older version

clang version 10.0.1 (https://github.com/OpenCilk/opencilk-project 8435006eea5d32f9cf895a666496b89613e2cbc1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/wheatman/SSTGraph_open_source/../OpenCilk-10.0.1-Linux/bin

**Comment by neboat** [comment]
This issue has been fixed in the latest release.
