### ISSUE TITLE
cilk assertion failed: deprived < nworkers

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#92]
### Describe the bug

My program crashes at runtime with the error `opencilk-project/cheetah/runtime/scheduler.c:1513: cilk assertion failed: deprived < nworkers`

### Expected behavior

For it to not crash, or tell me what is wrong 

### OpenCilk version

clang version 12.0.0 (https://github.com/OpenCilk/opencilk-project.git 5d2851d7d0e689ecb3b893aa6abd12390b838c4b)
Target: x86_64-unknown-linux-gnu
Thread model: posix

### System information

Ubuntu 18.04.6 LTS
Intel(R) Core(TM) i7-9750H

I am assuming that this is just an indication that I am scribbling over some memory I shouldn't, but in case it was something else I wanted to ask.  Also perhaps some of these asserts could have print statements that would indicate what the likely problem is

**Comment by VoxSciurorum** [comment]
It turned out that the assertion your code triggered was erroneous. For now you can comment out the assertion at line scheduler.c 1513.  We will have a proper fix in the next release.

**Comment by neboat** [comment]
This issue has been fixed in the latest release.
