### ISSUE TITLE
crash with cilk_sync after return

### ISSUE THREAD

**Issue by wheatman** [OpenCilk/opencilk-project#93]
### Describe the bug
If you put a cilk_sync after an unconditional return the compiler crashes.

### Expected behavior

I would expect that the cilk_sync, as well as any other code after an unconditional return to be ignored.

### OpenCilk version

https://github.com/OpenCilk/opencilk-project.git 5d2851d7d0e689ecb3b893aa6abd12390b838c4b 

### System information

Target: x86_64-unknown-linux-gnu

### Steps to reproduce (include relevant output)

The following code triggers the issue

```
#include <cilk/cilk.h>

int create() {
  return 1;
  cilk_sync;
}

int main([[maybe_unused]] int argc, char *argv[]) {
  int e = create();
  return 0;
}
```
compile with 
`../opencilk-project/build/bin/clang++ -Wall -Wextra -O3 -g  -fopencilk  -o basic basic.cpp`

It doesn't crash with -O0, but it does with 1-3

### Additional comments
I got a slightly different crash as part of a much larger code base, I will attach the output from that one as well, but this the simple one

[basic_backtrace.txt](https://github.com/OpenCilk/opencilk-project/files/8886560/basic_backtrace.txt)
[complicated_backtrace.txt](https://github.com/OpenCilk/opencilk-project/files/8886561/complicated_backtrace.txt)
[messey.cpp.txt](https://github.com/OpenCilk/opencilk-project/files/8886562/messey.cpp.txt)
[messey.sh.txt](https://github.com/OpenCilk/opencilk-project/files/8886563/messey.sh.txt)

**Comment by neboat** [comment]
Thanks for the bug report.  We have a fix for this that we'll deploy in the next release.

**Comment by neboat** [comment]
This issue has been fixed in the latest release.
